services:
  auto-build-deploy:
    build: .
    image: webhook-deployer
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_URL=https://github.com/c4software/bts-sio.git
    restart: unless-stopped